#!/usr/bin/env python

"""
    BS-SNV-Caller

    Copyright (C) Yance Feng
    Contact: Yance Feng <yance_feng@163.com>

The source code is licensed under the GPL version 3.

"""

import sys, os
from optparse import OptionParser

DIR=os.path.dirname(sys.argv[0])
#print DIR

import subprocess

VERSION = '1.1.0'

argv_len = len(sys.argv)

def print_version() :
   print("Version:  {VERSION}")
#

def print_usage() :
   print("Usage: BS-SNA-Caller --atcg sample.atcg.gz --output-prefix sample --mutation-rate 1/1000 --error-rate 3/100 --methy-cg 0.6 --methy-ch 0.01")

if (argv_len) == 1  or sys.argv[1] in ["-h", "-H", "--help"]:
   print("Single-Nucleotide Variant (SNV) calling with bisulfite-converted sequencing data")
   print_version()
else :
   subprocess.
