#!/usr/bin/env python

"""
    BS-SNV-Caller

    Copyright (C) Yance Feng
    Contact: Yance Feng <yance_feng@163.com>

The source code is licensed under the GPL version 3.

"""

import sys
import subprocess

########################
## version info

VERSION = '1.1.0'

INFO = "Ultra-fast and Accurate Single-Nucleotide Variant (SNV) calling with bisulfite-converted sequencing data for both single-cell and bulk samples"

# USAGE = "Usage: BS-SNA-Caller --atcg sample.atcg.gz --output-prefix sample [--mutation-rate 1/1000 --error-rate 3/100 --methy-cg 0.6 --methy-ch 0.01]"

########################



if sys.argv[1] in ["-V", "--version"]:
   print ("BS-SNV-Caller: version " + VERSION)
else :
   subprocess.run(sys.argv, shell=True)

